local colors = require("prism.themer"):getColors()
return {
  normal = { fg = colors.foreground, bg = colors.background },

  ellipsis = { fg = colors.cursorline },
  separator = { fg = colors.cursorline },
  modified = { fg = colors.cursorline },

  dirname = { fg = colors.foreground },
  basename = { fg = colors.foreground },
  context = { fg = colors.color15 },

  context_file = { fg = colors.color12 },
  context_module = { fg = colors.color12 },
  context_namespace = { fg = colors.color12 },
  context_package = { fg = colors.color12 },
  context_class = { fg = colors.color3 },
  context_method = { fg = colors.color12 },
  context_property = { fg = colors.color2 },
  context_field = { fg = colors.color2 },
  context_constructor = { fg = colors.color12 },
  context_enum = { fg = colors.color2 },
  context_interface = { fg = colors.color3 },
  context_function = { fg = colors.color12 },
  context_variable = { fg = colors.color5 },
  context_constant = { fg = colors.color9 },
  context_string = { fg = colors.color2 },
  context_number = { fg = colors.color9 },
  context_boolean = { fg = colors.color9 },
  context_array = { fg = colors.color12 },
  context_object = { fg = colors.color12 },
  context_key = { fg = colors.color5 },
  context_null = { fg = colors.color9 },
  context_enum_member = { fg = colors.color1 },
  context_struct = { fg = colors.color12 },
  context_event = { fg = colors.color12 },
  context_operator = { fg = colors.color12 },
  context_type_parameter = { fg = colors.color12 },
}
