local colors = require("prism.themer"):getColors()
local utils = require("prism.utils")

return {
  CmpItemKindClass = { bg = utils.darken(colors.color12, colors.darker, 0.1), fg = colors.color12 },
  CmpItemKindEnum = { bg = utils.darken(colors.color5, colors.darker, 0.1), fg = colors.color5 },
  CmpItemKindEnumMember = { bg = utils.darken(colors.color5, colors.darker, 0.1), fg = colors.color5 },
  CmpItemKindSnippet = { bg = utils.darken(colors.color10, colors.darker, 0.1), fg = colors.color10 },
  CmpItemKindField = { bg = utils.darken(colors.color10, colors.darker, 0.1), fg = colors.color10 },
  CmpItemKindText = { bg = utils.darken(colors.color12, colors.darker, 0.1), fg = colors.color12 },
  CmpItemKindConstant = { bg = utils.darken(colors.color11, colors.darker, 0.1), fg = colors.color11 },
  CmpItemKindConstructor = { bg = utils.darken(colors.color10, colors.darker, 0.1), fg = colors.color10 },
  CmpItemKindFunction = { bg = utils.darken(colors.color12, colors.darker, 0.1), fg = colors.color12 },
  CmpItemKindKeyword = { bg = utils.darken(colors.color5, colors.darker, 0.1), fg = colors.color5 },
  CmpItemKindOperator = { bg = utils.darken(colors.color12, colors.darker, 0.1), fg = colors.color12 },
  CmpItemKindProperty = { bg = utils.darken(colors.color5, colors.darker, 0.1), fg = colors.color5 },
  CmpItemKindStruct = { bg = utils.darken(colors.color12, colors.darker, 0.1), fg = colors.color12 },
  CmpItemKindTypeParameter = { bg = utils.darken(colors.color2, colors.darker, 0.1), fg = colors.color2 },
  CmpItemKindUnit = { bg = utils.darken(colors.color12, colors.darker, 0.1), fg = colors.color12 },
  CmpItemKindValue = { bg = utils.darken(colors.color10, colors.darker, 0.1), fg = colors.color10 },
  CmpItemKindVariable = { bg = utils.darken(colors.color1, colors.darker, 0.1), fg = colors.color1 },
  CmpItemAbbr = { fg = colors.foreground, },
  CmpItemAbbrDeprecated = { fg = colors.color2, },
  CmpItemAbbrMatch = { fg = colors.color7, },
  CmpItemAbbrMatchFuzzy = { fg = colors.color7, },
  CmpItemKind = { fg = colors.color12, },
  CmpItemMenu = { fg = colors.color12, },
  CmpDoc = { bg = colors.cursorline },
  Pmenu = { fg = colors.foreground, bg = colors.darker },
  PmenuSel = { bg = utils.darken(colors.color4, colors.darker, 0.4) },
  PmenuSbar = { bg = colors.darker },
  PmenuThumb = { bg = colors.color2 },
}
